wordpress:
  image: wordpress
  links:
    - mariadb:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=not-my-password
    - WORDPRESS_DB_USER=root
  ports:
    - "8083:80"
  volumes:
    - ./html:/var/www/html

mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=not-my-password
    - MYSQL_DATABASE=wordpress
  volumes:
    - ./database:/var/lib/mysql
